### ISSUE TITLE
[Question][Hw3] Where is a document related llvm::LLVMBuilder::CreateCall?

### ISSUE THREAD

**Issue by encrypted-def** [prosyslab-classroom/is511-2021-spring#11]
When I refer a `build_call` function from https://llvm.moe/ocaml/Llvm.html ,

website briefs explain what a function does and tells `See the method llvm::LLVMBuilder::CreateCall` to me.

But how can I find a document or explanation related `llvm::LLVMBuilder::CreateCall`? I tried to google it and searching from https://llvm.org/docs/GettingStartedTutorials.html , but I have no idea.

**Comment by KihongHeo** [comment]
LLVM's module names change frequently, so it may not yet updated properly, I guess.

You can search for `IRBuilder` and `CreateCall`.

**Comment by encrypted-def** [comment]
Thanks a lot!
