### ISSUE TITLE
[Question][Hw3] Error in command make

### ISSUE THREAD

**Issue by HwangSeongha** [prosyslab-classroom/is511-2021-spring#12]
When I enter 'make' command, the following error occurs.

Error: Library "llvm.irreader" not found.
Hint: try:
  dune external-lib-deps --missing src/main.exe
Makefile:8: recipe for target 'all' failed
make: *** [all] Error 1

So I tried to install conf-llvm 10.0.0 and llvm 10.0.0, I failed to install conf-llvm 10.0.0 since it does not have llvm-10-dev.

But I could not install llvm-10-dev by any ways I tried. May I ask how I can solve this problem?

**Comment by KihongHeo** [comment]
Have you tried `opam install llvm.10.0.0`?
Do you use your local machine?

I strongly recommend you use the provided environment.

**Comment by HwangSeongha** [comment]
Professor, I don't know why but some additional files such as example 1, 2, 3 or get-dock.sh is also pushed in my homework repository. Does it matter when scoring my assignment?? Thank you.

**Comment by hyunsikjeong** [comment]
Those example files are just examples to test your code. You can use it to test basic test cases.
We never pushed a file named get-dock.sh. Check your commit history.
Scoring will be done by using your code.

**Comment by hyunsikjeong** [comment]
Closing the issue.
