### ISSUE TITLE
Could not use Llvm in utop

### ISSUE THREAD

**Issue by hdtuanss** [prosyslab-classroom/is511-2021-spring#13]
Hi,
I try to use Llvm in utop by: "open Llvm;;"   but it returns: "Error: Unbound module Llvm".
I have checked the environment and the dependencies have been installed right version:
llvm-config --version : 10.0.0
opt --version: LLVM version 10.0.0
clang --version: clang version 10.0.0-4ubuntu1~18.04.2

Please help me with my problem
Thank you!

**Comment by KihongHeo** [comment]
`utop` is just a simple REFL (interpreter), not suitable for complicated programming.
Please try to build and execute the code.

**Comment by hdtuanss** [comment]
Yes I got it. Thank you so much!
