### ISSUE TITLE
[Question][Hw3] Can I late-commit more though I had committed codes in time?

### ISSUE THREAD

**Issue by whkim0** [prosyslab-classroom/is511-2021-spring#14]
I have committed Hw3 yesterday (5/5), but I want to submit better performing code.
As far as i know, I'm allowed for 5 grace days, so is it allowed to commit more codes after the deadline?

**Comment by ihwong** [comment]
Yes. TAs will check your grace day use (ex. 1 day if you commit today) and grade your last commit.
