### ISSUE TITLE
[Question][Hw4] Question about HW4

### ISSUE THREAD

**Issue by bbb1g** [prosyslab-classroom/is511-2021-spring#16]
Q. Can I branch mutation logic based on target filename?
What I mean is, Can you guarantee that the filename will be same as test directory in the evaluation?

for instance, 
```
if "json_parser" = env.exe then
  mutate_json ~~
else
  mutate_default ~~
```

**Comment by hyunsikjeong** [comment]
I think TAs cannot answer this question. @KihongHeo Could you answer this?

**Comment by KihongHeo** [comment]
Good idea. Unfortunately, the filename is not guaranteed.
But I believe you can do the thing in a different way.

**Comment by bbb1g** [comment]
I think I clearly understood about it.

Thanks for answers.!!
