### ISSUE TITLE
[Question][Hw4]Make error on test

### ISSUE THREAD

**Issue by gold9598** [prosyslab-classroom/is511-2021-spring#19]
When I tried to use make, error occurred :
PHI nodes not grouped at top of basic block!
  %string_length.7 = phi i32 [ %string_length.0, %sw.epilog846 ], [ %string_length.6, %sw.epilog1129 ], !dbg !1364
label %if.end1130
PHI nodes not grouped at top of basic block!
  %cond = phi i8* [ %call, %cond.true ], [ %call1, %cond.false ], !dbg !1534
label %cond.end
fatal error: error in backend: Broken module found, compilation aborted!
clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
Ubuntu clang version 10.0.1-++20210405103842+ef32c611aa21-1~exp1~20210405084441.211
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/runtime-a8a490.c
clang: note: diagnostic msg: /tmp/runtime-a8a490.sh
clang: note: diagnostic msg: 

How should I handle it?
Thank you.

**Comment by ihwong** [comment]
Hello, gold9598. Could you please take a look at this [post](https://github.com/prosyslab-classroom/cs448-2021-spring/issues/94)? If the same problem still occurs, please let us know :)

**Comment by gold9598** [comment]
Solved. Thanks!
