### ISSUE TITLE
[Question][Hw4] json_parser's running time is massively slow

### ISSUE THREAD

**Issue by encrypted-def** [prosyslab-classroom/is511-2021-spring#20]
When I check `json_parser.c` file, there is no heavy time-consuming computation.

However, for me, json_parser's running time is massively slow.

```sh
$ time ./json_parser < json_seed/seed_2.json
real    0m5.409s
user    0m0.080s
sys     0m0.835s

$ time ./json_parser < json_seed/seed_2.json
real    0m5.369s
user    0m0.074s
sys     0m0.841s

$ time ./json_parser < json_seed/seed_2.json
real    0m5.478s
user    0m0.109s
sys     0m0.835s
```

I cannot easily catch the reason. Even if my sanitizer is implement in weird way, `json_parser.instrumented.ll` may same as others, so it won't be a reason for running time.

Is there anyone who suffers with same thing?

**Comment by hyunsikjeong** [comment]
FYI, students of a previous class haven't encountered this issue.

**Comment by encrypted-def** [comment]
It could be my local problem. I'm little worried that my json_parser executable also runs slow while judging.

But anyway, HW is submitted and seems it's not something I can do right away. Thank you.
