### ISSUE TITLE
[Question][Hw5] Semantics of `sanitizer()`

### ISSUE THREAD

**Issue by hyunsukimsokcho** [prosyslab-classroom/is511-2021-spring#22]
I would like to ask two questions about semantics of `sanitizer()` function.

1. Is the semantics of `sanitizer()` to be fixed as a single abstract value? In skeleton, type of `of_sanitizer` takes no parameter into account. I guess we can do better(?) in terms of `SIGN` domain. I just want to make sure if this is intended for simplicity. 

2. In [12th week lecture slides](https://drive.google.com/file/d/1Sc5J10rUvL40yjk9uWtRTg5ZjadFWP5s/view), there is an example showing how `sanitizer()` function works and I found one to be a bit spurious. Below is the third example in 16th page:

![image](https://user-images.githubusercontent.com/44839562/119756309-53a0db00-bede-11eb-89a9-7179179de9fe.png)

`sink(z)` in the last line shall be SAFE as joined value of `z` from two branches are both sanitized.

Please correct me if I got wrong or missed anything.

**Comment by KihongHeo** [comment]
1. In the README file, I defined the semantics informally: "unknown and untainted integer". I don't know how you improve this more.
2. This is a typo. I explained that in the lecture with a fixed slide. I updated the slide deck and lecture video. See the new example.

**Comment by hyunsukimsokcho** [comment]
I see the point, thanks for the clarifications. Now closing.
