### ISSUE TITLE
[Question][Hw5] About Unreachable Code

### ISSUE THREAD

**Issue by HwangSeongha** [prosyslab-classroom/is511-2021-spring#26]
filter function in Semantics.ml returns an abstract memory that satisfies given condition.
According to instruction, filter (x < 10) true mem will return an abstract memory that satisfies condition x < 10.
However, in example1.c, 

> int main() {
>   int x = source();
>   int z;
>   if (x >= 0) {
>     z = 10 / x; // error
>     if (x < 0) {
>       z = 10 / x; // unreachable
>     }
>   } else {
>     z = 10 / x; // safe
>   }
>   z = 10 / x; // error
>   return 0;
> }
> 

Then filter (x>=0) true mem return memory (x->Top), and (x<0) true mem return memory (x->Neg) since x remains Top in the memory. Then the code 
>       z = 10 / x; // unreachable
becomes reachable. Could you give an advice how I can solve this problem?

**Comment by hyunsikjeong** [comment]
I think you're understading right. It's not solvable with Sign domain I guess.
