### ISSUE TITLE
[Question][Hw5] About Example3.c

### ISSUE THREAD

**Issue by HwangSeongha** [prosyslab-classroom/is511-2021-spring#27]
```
int main() {
  int i;
  int sum = 0;
  int z;
  for (i = 10; i > 1; i--) {
    sum = 10 / i;
  }
  z = 10 / (i - 1); // safe by interval with narrowing, false alarm by sign
  z = 10 / i;       // error
  return 0;
}
```

About above code, it says `z = 10 / i;` has potential error in sign domain.
However, the variable i comes from for loop, and i should be Pos by its condition i > 1. 
I wonder why it has potential error, and also wonder the logic. Could you give an advice?

**Comment by hyunsikjeong** [comment]
`i--` makes `i` as `Top`, and `i <= 1` cannot filter well. `i` will be `Top` after the loop.

**Comment by HwangSeongha** [comment]
Thank you for comment.
