### ISSUE TITLE
[Question][Hw5] About Taint Analysis Report

### ISSUE THREAD

**Issue by bbb1g** [prosyslab-classroom/is511-2021-spring#28]
분석 결과를 report할 때 `analysis.ml`의 `check`함수를 사용하는데,
`check_instr`와 `check`는 이미 구현되어 있는 코드를 사용하여 report를 하였습니다.

하지만 `check_instr`는 sign analysis와 taint analysis의 구분이 없어 taint analysis를 report할 때
아래 코드로 인해 invalid division by zero report가 발생합니다.
`if Memory.Value.order zero v then`

이와 같은 경우는 고려하지 않아도 되는 것인지 여쭙고 싶습니다.
감사합니다.

**Comment by hyunsikjeong** [comment]
@KihongHeo 중요한 이슈 같아서 태그 남깁니다.

**Comment by KihongHeo** [comment]
No worries. We will have separated test sets.

**Comment by bbb1g** [comment]
답변 감사합니다.
