### ISSUE TITLE
[Question][Hw3] clang does not know -fno-discard-value-names option.

### ISSUE THREAD

**Issue by gold9598** [prosyslab-classroom/is511-2021-spring#7]
I have a question about running the clang on the example.
when I tried to use the script that
clang -c -emit-llvm -S -fno-discard-value-names -Xclang -disable-O0-optnone -o example1.tmp.ll -g example1.c,
clang omitted error that
unknown argument: '-fno-discard-value-names'.

How should I solve it?
Thanks.

**Comment by hyunsukimsokcho** [comment]
Which version of clang are you using? (`clang -v`)

**Comment by gold9598** [comment]
> Which version of clang are you using? (`clang -v`)

Oh, previously 6.0. After I updated with 10.0 and then overwrite the binary name, It runs. Thanks!
